//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwormsWpf.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public int ItemGenre { get; set; }
        public int ItemAuthor { get; set; }
        public double ItemCost { get; set; }
        public string ItemDescription { get; set; }
        public string ItemPhotoString { get; set; }
        public byte[] ItemPhotoByte { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
